config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount Motor::Admin => '/motor_admin'

  resources :films, only: [:index, :update]

  resources :films do
    resources :reviews, only: [:index, :new, :create]
  end

  resources :reviews, only: [:show, :edit, :update, :destroy]

  root to: "films#index"
  resources :users, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/film.rb
class Film < ApplicationRecord
  has_one_attached :photo
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :film

  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: %i[ show edit update destroy ]

  # Code for Devise
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  # GET /films or /films.json
  def index
    @films = Film.order(title: :asc)

    if params[:query].present?
      @films= @films.where("title ILIKE ?", "%#{params[:query]}%")
    end

    respond_to do |format|
      format.html
      format.text { render partial: "films/list", locals: {films: @films}, formats: [:html] }
    end
  end

  # GET /films/1 or /films/1.json
  def show
  end

  # GET /films/new
  def new
    @film = Film.new
  end

  # GET /films/1/edit
  def edit
  end

  # POST /films or /films.json
  def create
    @film = Film.new(film_params)

    respond_to do |format|
      if @film.save
        format.html { redirect_to film_url(@film), notice: "Film was successfully created." }
        format.json { render :show, status: :created, location: @film }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1 or /films/1.json
  def update
    @film = Film.find(params[:id])
    @film.update(film_params)

    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to film_url(@film), notice: "Film was successfully updated." }
        format.json { render :show, status: :ok, location: @film }
        format.text { render partial: "films/film_infos", locals: {film: @film}, formats: [:html] }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1 or /films/1.json
  def destroy
    @film.destroy

    respond_to do |format|
      format.html { redirect_to films_url, notice: "Film was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def film_params
      params.require(:film).permit(:title, :body, :photo)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # to find the film associated with the review, the following controller code is implemented
  before_action :set_film, only: %i[new create]


  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.film = @film
    if @review.save
      redirect_to film_path(@film)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to film_path(@review.film), status: :see_other
  end

  private

  def set_film
    @film = Film.find(params[:film_id])
  end

  def review_params
    params.require(:review).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  

  def index@users = User.all
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/films/_film.html.erb
<div id="<%= dom_id film %>">
  <p>
    <strong>Title:</strong>
    <%= film.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= film.body %>
  </p>

</div>

app/views/films/_film_infos.html.erb
<div class="film-card" data-controller="edit-film" data-edit-film-target="card">

  <div class="film-infos <%= 'd-none' if film.errors.any? %>" data-edit-film-target="infos">
    <h2><%= film.title %></h2>
    <button aria-label="Edit film">
      <i class="fa-solid fa-pen fa-xs ml-2" data-action="click->edit-film#displayForm"></i>
    </button>
  </div>

  <%= simple_form_for film,
    html: {
      class: film.errors.any? ? "" : "d-none",
      data: {
        edit_film_target: "form",
        action: "submit->edit-film#update"
      }
    } do |f|
  %>
    <%= f.input :title %>
    <%= f.input :body %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Update film", class: "btn btn-sm btn-primary btn-block mt-2" %>
  <% end %>
</div>

app/views/films/_form.html.erb
<%= simple_form_for(@film) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body %>
    <%= f.input :photo, as: :file %>
  </div>

  <div class="form-actions">
      <%= f.button :submit, class: "btn btn-primary create-button" %>
  </div>
<% end %>

app/views/films/_list.html.erb
<div data-refresh-list-target="list">
  <% if params[:query].blank? %>
    <h1 class="h3"><%= pluralize films.count, 'film' %> available</h1>
  <% else %>
    <h1 class="h3"><%= pluralize films.count, 'result' %> for <code><%= params[:query] %></code></h1>
  <% end %>
  <div class="films">
    <% films.each do |film| %>
      <div class="film-card">
        <%= image_tag film.image_url %>
        <h2><%= film.title %> <small>(<%= film.year %>)</small></h2>
      </div>
    <% end %>
  </div>
</div>

app/views/films/edit.html.erb
<h1>Editing film</h1>

<%= render "form", film: @film %>

<br>

<div>
  <%= link_to "Show this film", @film %> |
  <%= link_to "Back to films", films_path %>
</div>

app/views/films/index.html.erb
<p class="notice"><%= notice %></p>

<header role="banner" aria-label="Cinema Today" class="ms-3">
  <h1>Cinema Today</h1>
</header>

<div class="text-center">
  <p><span data-controller="typed-js"></span></p>
</div>

<div class="text-center fs-4">
  <h2><i class="fas fa-film me-2"></i>Films</h2>
</div>

<%= link_to new_film_path, class: "d-flex justify-content-center my-3" do %>
  <button class="btn btn-success" type="button">New film</button>
<% end %>

<div data-controller="refesh-list">
  <%= form_with url: films_path, method: :get, html: {class:
    "mb-5", data: {refresh_list_target: "form"}} do |f| %>
    <%= f.text_field :query, class: "form-control", placeholder:
                     "Type a film title", value: params[:query],
                     data: {
                        refresh_list_target: "input",
                        action: "keyup->refresh-list#update"
                      } %>

<% if @films.any? %>
  <div class="container">
    <div class="row justify-content-center">
      <% @films.each do |film| %>
        <div class="col-12 col-sm-6 col-md-4 col-lg-3">
          <div class="card">
            <%= render film %>
            <div class="card-body d-flex justify-content-center">
              <%= link_to film_path(film), class: "btn btn-primary" do %>
                Show this film
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% else %>
  <p>No results found for "<%= params[:query] %>"</p>
<% end %>
  <div data-refresh-list-target="list">
<% end %>

app/views/films/new.html.erb
<div class="film-title">
  <h1>New film</h1>
</div>

<div class="film-icon">
  <i class="fa-solid fa-film"></i>
</div>

<div class="film-form">
  <%= render "form", film: @film %>
</div>

<div class="film-back-link">
  <%= link_to "Back to films", films_path %>
</div>

app/views/films/shared/_confirm.html.erb
<dialog id="turbo-confirm">
  <form method="dialog">
    <h3 data-behavior="title">Are you sure?</h3>

    <div data-behavior="description"></div>
    <input data-behavior="confirm-text" />

    <div>
      <button value="cancel">Cancel</button>
      <button value="confirm">Confirm</button>
    </div>
  </form>
</dialog>

app/views/films/show.html.erb
<div class="text-center">
  <p style="notice-green"><%= notice %></p>
  <main class="flex-shrink-0">
    <div class="container">
      <%= render @film %>
      <% if @film.photo.present? %>
        <%= cl_image_tag @film.photo.key, height: 300, width: 400, crop: :fill %>
      <% end %>
      <div>
        <%= link_to "Edit this film", edit_film_path(@film), class: "btn btn-primary" %>  |
        <%= link_to "Back to films", films_path, class: "btn btn-secondary" %>

        <%= button_to "Delete this film", @film, method: :delete, form: {
          data: {
            turbo_confirm: "Are you sure?",
            turbo_confirm_text: @film.title,
            turbo_confirm_description: "This action cannot be undone. Enter the film title to confirm."
          }
        } %>
      </div>
      <p><strong>Reviews</strong></p>
      <ul class="list-group">
        <% @film.reviews.each do |review| %>
          <li class="list-group-item"><%= review.content %>
            <%= review.content %>
            <%= link_to "Delete",
              review_path(review),
              data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
          </li>
        <% end %>
      </ul>
<br>
    </div>
  </main>

   <dialog id="turbo-confirm">
     <div class="dialog-content">
      <h2 class="dialog-title"></h2>
      <p class="dialog-description"></p>
      <input type="text" class="confirm-text" placeholder="Enter film title">
      <div class="dialog-buttons">
        <button class="confirm-button" value="confirm">Confirm</button>
        <button class="cancel-button" value="cancel">Cancel</button>
      </div>
    </div>
  </dialog>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer mt-auto py-3 bg-light">
  <div class="container">
    <span class="text-muted"><span data-controller="copyright"></span>
      Cinema Today. All Rights Reserved.</span>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <title>CinemaToday</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body  class="d-flex flex-column h-100">
    <main class="flex-shrink-0">
      <div class="container">
       <%= render "shared/flashes" %>
        <%= render "shared/navbar" %>
        <%= yield %>

        <%= render "shared/confirm" %>
      </div>
    </main>
    <%# <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-emoji-heart-eyes" viewBox="0 0 16 16"><path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/><path d="M11.315 10.014a.5.5 0 0 1 .548.736A4.498 4.498 0 0 1 7.965 13a4.498 4.498 0 0 1-3.898-2.25.5.5 0 0 1 .548-.736h.005l.017.005.067.015.252.055c.215.046.515.108.857.169.693.124 1.522.242 2.152.242.63 0 1.46-.118 2.152-.242a26.58 26.58 0 0 0 1.109-.224l.067-.015.017-.004.005-.002zM4.756 4.566c.763-1.424 4.02-.12.952 3.434-4.496-1.596-2.35-4.298-.952-3.434zm6.488 0c1.398-.864 3.544 1.838-.952 3.434-3.067-3.554.19-4.858.952-3.434z"/></svg> %>
    <%= render partial: "layouts/footer" %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/reviews/new.html.erb
<h1>Create a New review</h1>
<%= simple_form_for [@film, @review] do |f| %>
  <%= f.input :content %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>

app/views/reviews/show.html.erb
<h1><center>This page will soon display a Reviews creation page</center> </h1>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to "Films", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <%= link_to "New film", new_film_path, class: "nav-item nav-link" %>
        <%# <%= link_to 'New Review', new_film_review_path(@film) %>
      </ul>

      <ul class="navbar-nav mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <%= link_to current_user.email, edit_user_registration_path, class: "nav-item nav-link" %>
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-item nav-link" %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, class: "nav-item nav-link" %>
          <%= link_to "Login", new_user_session_path, class: "nav-item nav-link" %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/users/index.html.erb
<h1>Cinema Today users screen</h1>